
---
output:
  md_document:
    variant: markdown_github
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "##",
  fig.path = "README-")
```

##lexvarsdatr

Description.  Just get this clean.  Fix as need be per development of workshop.


Data included in package:
```{r echo=FALSE, message=FALSE, warning=FALSE}
library(knitr)
type <- c("CELEX","Lexical decision and naming","Concreteness ratings","AoA ratings", "Word association")

bib <- c("Baayen, R. H., Piepenbrock, R., & Gulikers, L. (1995). The CELEX lexical database [webcelex]. *Philadelphia, PA: University of Pennsylvania, Linguistic Data Consortium*.", "Balota, D. A., Yap, M. J., Hutchison, K. A., Cortese, M. J., Kessler, B., Loftis, B., ... & Treiman, R. (2007). The English lexicon project. *Behavior research methods*, 39(3), 445-459.","Brysbaert, M., Warriner, A. B., & Kuperman, V. (2014). Concreteness ratings for 40 thousand generally known English word lemmas. *Behavior research methods*, 46(3), 904-911.","Kuperman, V., Stadthagen-Gonzalez, H., & Brysbaert, M. (2012). Age-of-acquisition ratings for 30,000 English words. *Behavior Research Methods*, 44(4), 978-990.","Nelson, D. L., McEvoy, C. L., & Schreiber, T. A. (2004). The University of South Florida free association, rhyme, and word fragment norms. *Behavior Research Methods, Instruments, & Computers*, 36(3), 402-407.")

kable(data.frame(type=type,bib=bib))
```


```{r warning=FALSE, paged.print=FALSE}
library(tidyverse)
#devtools::install_github("jaytimm/lexvarsdatr")
library(lexvarsdatr)
```


Perhaps we bury this for the time being -- ???

##CELEX functions
```{r}
lexvarsdatr::lvdr_get_family(form="think",type="V") %>%
  unlist()%>%
  paste()
```

##Behavioral data
Age-of-acquisition
```{r}
lexvarsdatr::lvdr_behav_data %>%
  filter(!is.na(aoaRating)) %>%
  arrange(aoaRating)%>%
  mutate(cum = row_number())%>%
  ggplot(aes(x=aoaRating, y = cum)) +
  geom_line()
```


```{r}
lexvarsdatr::lvdr_behav_data %>%
  filter(concRating > 4.5, aoaRating > 15)%>%
  select(Word)%>%
  unlist()%>%
  paste()
```


